# Importing Modules

In [303]:
import random
import pandas as pd
from operator import itemgetter

# Store information about teams and players.

In [304]:
Mumbai_India = ['Mumbai_India',r'E:\\IIT\\1st Year\\1st Trimester\\CM1601 [PRO]  Programming Fundamentals\\Course Work\\team_data\\Mumbai_India\\Mumbai_India.xlsx']
Chennai_SouthAfrica = ['Chennai_SouthAfrica',r'E:\\IIT\\1st Year\\1st Trimester\\CM1601 [PRO]  Programming Fundamentals\\Course Work\\team_data\\Chennai_SouthAfrica\\Chennai_SouthAfrica.xlsx']
Delhi_NewZealand = ['Delhi_NewZealand',r'E:\\IIT\\1st Year\\1st Trimester\\CM1601 [PRO]  Programming Fundamentals\\Course Work\\team_data\\Delhi_NewZealand\\Delhi_NewZealand.xlsx']
RoyalChallengers_Bangladesh = ['RoyalChallengers_Bangladesh',r'E:\\IIT\\1st Year\\1st Trimester\\CM1601 [PRO]  Programming Fundamentals\\Course Work\\team_data\\RoyalChallengers_Bangladesh\\RoyalChallengers_Bangladesh.xlsx']
Rajastan_Australia =  ['Rajastan_Australia',r'E:\\IIT\\1st Year\\1st Trimester\\CM1601 [PRO]  Programming Fundamentals\\Course Work\\team_data\\Rajastan_Australia\\Rajastan_Australia.xlsx']
Kolkata_England = ['Kolkata_England',r'E:\\IIT\\1st Year\\1st Trimester\\CM1601 [PRO]  Programming Fundamentals\\Course Work\\team_data\\Kolkata_England\\Kolkata_England.xlsx']
Punjab_Pakistan = ['Punjab_Pakistan',r'E:\\IIT\\1st Year\\1st Trimester\\CM1601 [PRO]  Programming Fundamentals\\Course Work\\team_data\\Punjab_Pakistan\\Punjab_Pakistan.xlsx']
Sunrisers_SriLanka = ['Sunrisers_SriLanka',r'E:\\IIT\\1st Year\\1st Trimester\\CM1601 [PRO]  Programming Fundamentals\\Course Work\\team_data\\Sunrisers_SriLanka\\Sunrisers_SriLanka.xlsx']

# the user can delete/edit player and team profiles and system needs to give separate options for each and every functionality

# points table

In [305]:
# https://www.freecodecamp.org/news/how-to-create-read-update-and-search-through-excel-files-using-python-c70680d811d4/

In [306]:
# import openpyxl

# myworkbook = load_workbook(r'E:\\IIT\\1st Year\\1st Trimester\\CM1601 [PRO]  Programming Fundamentals\\Course Work\\team_data\\points_table.xlsx')
# worksheet= myworkbook['Sheet1']

# worksheet['F1']='We are writing to B4'

In [307]:
# import openpyxl

# theFile = openpyxl.load_workbook(r'E:\\IIT\\1st Year\\1st Trimester\\CM1601 [PRO]  Programming Fundamentals\\Course Work\\team_data\\points_table.xlsx')
# allSheetNames = theFile.sheetnames

# print("All sheet names {} " .format(theFile.sheetnames))


# for sheet in allSheetNames:
#     print("Current sheet name is {}" .format(sheet))
#     currentSheet = theFile[sheet]
#     # print(currentSheet['B4'].value)

#     #print max numbers of rows and columns for each sheet
#     #print(currentSheet.max_row)
#     #print(currentSheet.max_column)

#     for row in range(1, currentSheet.max_row + 1):
#         #print(row)
#         for column in "B":  # Here you can add or reduce the columns
#             cell_name = "{}{}".format(column, row)
#             #print(cell_name)
#             print("cell position {} has value {}".format(cell_name, currentSheet[cell_name].value))
#             # ws[cell_name] = 4
#             currentSheet[cell_name] = 4

In [308]:
# import pandas as pd
# from openpyxl import load_workbook

# wb = load_workbook(r'E:\\IIT\\1st Year\\1st Trimester\\CM1601 [PRO]  Programming Fundamentals\\Course Work\team_data\\points_table.xlsx')
# ws = wb.active


# for row in ws.values:
#    for value in row:
#      print(value)

# Generate random match:

In [309]:
# import random


#assinging 
Group_A = [Mumbai_India,Chennai_SouthAfrica,Delhi_NewZealand,RoyalChallengers_Bangladesh ]
Group_B = [Rajastan_Australia,Kolkata_England,Punjab_Pakistan,Sunrisers_SriLanka]



match_between_A = random.sample(Group_A, 2)
match_between_B = random.sample(Group_B, 2)



chosen_match = [match_between_A,match_between_B]
match_between = random.choice(chosen_match)


print(match_between)

[['RoyalChallengers_Bangladesh', 'E:\\\\IIT\\\\1st Year\\\\1st Trimester\\\\CM1601 [PRO]  Programming Fundamentals\\\\Course Work\\\\team_data\\\\RoyalChallengers_Bangladesh\\\\RoyalChallengers_Bangladesh.xlsx'], ['Delhi_NewZealand', 'E:\\\\IIT\\\\1st Year\\\\1st Trimester\\\\CM1601 [PRO]  Programming Fundamentals\\\\Course Work\\\\team_data\\\\Delhi_NewZealand\\\\Delhi_NewZealand.xlsx']]

# The team who won the toss takes the decision (Ball first or bat first)

In [310]:
# import random

coin = ["heads", "tails"]
options = ['bat','bowl']
team_to_bat = []
team_to_bowl = []

visiting_team = random.choice(match_between)

if visiting_team in match_between:
    match_between.remove(visiting_team)

home_team = match_between[0]


toss = random.choice(coin)            # This simulates the coin being tossed
choose = random.choice(options)       # This simulates the visiting team choose bat or bowl
selection = random.choice(coin)       # This simulates the visiting team choose head or tails

print('Home Team', home_team[0])
print('Visiting Team', visiting_team[0])

if selection == toss:
    print(visiting_team[0], 'won the toss and chose to', choose)
    if choose == options[0]:
        team_to_bat = visiting_team
        team_to_bowl = home_team
    else:
        team_to_bat = home_team
        team_to_bowl = visiting_team
    
else:
    print(home_team[0], 'won the toss and chose to', choose)
    if choose == options[0]:
        team_to_bat = home_team
        team_to_bowl = visiting_team
    else:
        team_to_bat = visiting_team
        team_to_bowl = home_team

Home Team Delhi_NewZealand
Visiting Team RoyalChallengers_Bangladesh
Delhi_NewZealand won the toss and chose to bowl

In [311]:

print('team_to_bat', team_to_bat[0])
print('team_to_bowl', team_to_bowl[0])

team_to_bat RoyalChallengers_Bangladesh
team_to_bowl Delhi_NewZealand

# Then program initiates the first innings.
# Scores of each batsman, balls took for scoring, wickets by bowlers, overs, fall of wickets, the method of the dismissal, final score of the innings

In [312]:
# import random
# import pandas as pd
# from operator import itemgetter


first_ing_total = 0
first_ing_wickets = 0
balls = 1
TOTAL_WICKETS = 10
TOTAL_BALLS = 120
score_card_first_ing = []


batsman_onstrike = [['name', 0, 0], True]
batsman_offstrike = [['name', 0, 0], False]


bowler_onstrike = []



# batsman_name , runs , balls_faced , method of dismissal , bowler
#importing batting team
batting_url = team_to_bat[1]
batting_team = pd.read_excel(batting_url)
#converting excel to python list
yet_to_bat = batting_team.values.tolist()        

# bowlers_name , balls , runs , wickets
#importing bowling team
bowling_url = team_to_bowl[1]
bowling_team = pd.read_excel(bowling_url)
#converting excel to python list
bowling_team_list = bowling_team.values.tolist()  


yet_to_bowl = []

for i in reversed(range(len(bowling_team_list))):
    if len(yet_to_bowl) < 5 :
        yet_to_bowl.append([bowling_team_list[i][0], 0, 0, 0])



dismissed_batsmen = []
batsman_list = []



# method of dismissal
method_of_dismissal = ['Bowled', 'Caught', 'LBW']


bowler_score = 0  # score counting variable for bowler
batter_score = 0  # score counting variable for batsman


# opening batsmen coming to the field
batsman_onstrike[0] = yet_to_bat.pop(0)
batsman_offstrike[0] = yet_to_bat.pop(0)


# opening bowler
bowler_onstrike = yet_to_bowl.pop(0)


while (balls < (TOTAL_BALLS+1)):
    if first_ing_wickets == TOTAL_WICKETS:
        break
    else:
        if ((balls-1) > 0 and (balls-1) % 6 == 0) and (len(yet_to_bowl)) > 0:
            yet_to_bowl.append(bowler_onstrike)
            # bowler_onstrike[0] = []
            bowler_onstrike = yet_to_bowl.pop(0)

        # get random scores for bowler and batsman
        bowler_score = random.randint(1, 6)
        batter_score = random.randint(0, 6)

        if bowler_score == batter_score:
            # adding wickets to bowler
            current_bowler_onstrike_first_ing_wickets = 0
            current_bowler_onstrike_first_ing_wickets = bowler_onstrike[3]
            bowler_onstrike[3] = current_bowler_onstrike_first_ing_wickets + 1
            # adding balls to batsman
            current_batsman_onstrike_balls = batsman_onstrike[0][2]
            batsman_onstrike[0][2] = current_batsman_onstrike_balls + 1

            # moving the dismissed_batsmen to dismissed_batsmen array
            dismissed_batsmen.append(batsman_onstrike[0])


            # adding method of dismissal to batsman
            current_batsman_method_of_dismissal = random.choices(
                method_of_dismissal)
            batsman_onstrike[0][3] = current_batsman_method_of_dismissal[0]

            # adding dismissed bowler name to batsman
            current_batsman_bowler_dismissed = batsman_onstrike[0][4]
            batsman_onstrike[0][4] = current_batsman_bowler_dismissed + \
                str(bowler_onstrike[0])

            # fall of wickets
            print('FOW', first_ing_total, ' --> ', first_ing_wickets+1, ' on over -', int(balls/6), '.', (balls) % 6 , batsman_onstrike[0][0])

            #bring new batsman to the crease (batsman_onstrike)
            if len(yet_to_bat) > 0:
                batsman_onstrike[0] = []
                batsman_onstrike[0] = yet_to_bat.pop(0)


            # out - add wicket to wickets
            first_ing_wickets += 1



        else:
            # adding batter_score to current_batsman
            current_batsman_onstrike_score = 0
            current_batsman_onstrike_score = batsman_onstrike[0][1]
            batsman_onstrike[0][1] = current_batsman_onstrike_score + batter_score

            # adding balls to current_batsman
            current_batsman_onstrike_balls = batsman_onstrike[0][2]
            batsman_onstrike[0][2] = current_batsman_onstrike_balls + 1

            # adding batter_score to current_bowler
            current_bowler_onstrike_runs = 0
            current_bowler_onstrike_runs = bowler_onstrike[2]
            bowler_onstrike[2] = current_bowler_onstrike_runs + batter_score

            # swapping onstrike batsman when strike rotates
            if batter_score == 1 or batter_score == 3:
                current_batsman = batsman_onstrike[0]
                # swapping onstrike batsman
                batsman_onstrike[0] = batsman_offstrike[0]
                batsman_offstrike[0] = current_batsman
            else:
                pass  # when batter_score is not swapping

            # add batter score to first_ing_total
            first_ing_total += batter_score

    # adding balls to bowler
    current_bowler_onstrike_balls = 0
    current_bowler_onstrike_balls = bowler_onstrike[1]
    bowler_onstrike[1] = current_bowler_onstrike_balls + 1
    balls += 1

# last dismissed batsman
last_dismissal = dismissed_batsmen[-1]
# print('Last dismissal', last_dismissal)

#add dismissed_batsmen to batsman_list
batsman_list = dismissed_batsmen

#add each batsman in yet_to_bat to batsman_list array for displaying purposes
if len(yet_to_bat) > 0 :
    for i in range(len(yet_to_bat)):
        batsman_list.append(yet_to_bat[i])

#add on and off strike batsmen to batsman_list
if first_ing_wickets != TOTAL_WICKETS:
    batsman_onstrike[0][3] = '* NOT OUT'
    batsman_list.append(batsman_onstrike[0])

batsman_offstrike[0][3] = 'NOT OUT'
batsman_list.append(batsman_offstrike[0])

#add batsman_list to score_card_first_ing
score_card_first_ing = batsman_list


# Total
# print(' Total-', first_ing_total, ' wickets -', first_ing_wickets, ' overs -', int((balls-1)/6), '.', (balls-1) % 6, ' balls', (balls-1))


# sort score_card_first_ing to the original batting order
sorted_list = sorted(score_card_first_ing, key=itemgetter(5))


# Print score_card_first_ing in a data frame
df_score_card_first_ing = pd.DataFrame(sorted_list)
# print(df_score_card_first_ing)


#add bowlers to bowler_list_first_ing
bowler_list_first_ing = yet_to_bowl
bowler_list_first_ing.append(bowler_onstrike)

df_bowler_list_first_ing = pd.DataFrame(bowler_list_first_ing)
# print(df_bowler_list_first_ing)

FOW 10  -->  1  on over - 0 . 4 Liton Das
FOW 19  -->  2  on over - 1 . 2 Mohammad Niam
FOW 40  -->  3  on over - 2 . 5 Shakib Al Hasan
FOW 55  -->  4  on over - 4 . 1 Mahmudulla(C)
FOW 70  -->  5  on over - 5 . 1 Afif Hossain
FOW 70  -->  6  on over - 5 . 2 Shamim Hossain
FOW 92  -->  7  on over - 6 . 5 Mahedi Hasan
FOW 124  -->  8  on over - 8 . 4 Mushfiqur Rahim
FOW 170  -->  9  on over - 12 . 1 Taskin Ahmed
FOW 190  -->  10  on over - 13 . 2 Mustafizur Rahman

In [313]:
print('\nTotal-', first_ing_total, '\nwickets -', first_ing_wickets, '\novers -', int((balls-1)/6), '.', (balls-1) % 6, '\nballs', (balls-1))
print('\nLast dismissal', last_dismissal)

Total- 190
wickets - 10
overs - 13 . 2
balls 80

Last dismissal ['Mustafizur Rahman', 39, 17, 'Bowled', ' Adam Milne', 10]

In [314]:
new_headers = ['Batting','Runs','Balls Faced','MOD','Bowler','Batting No']
df_score_card_first_ing.columns = new_headers
df_score_card_first_ing_without_index = df_score_card_first_ing.set_index('Batting')
df_score_card_first_ing_without_index

                   Runs  Balls Faced      MOD             Bowler  Batting No
Batting
Mohammad Niam         9            4   Bowled        Tim Southee           1
Liton Das             7            3   Bowled        Trent Boult           2
Shakib Al Hasan       4            4   Caught          Ish Sodhi           3
Mushfiqur Rahim      70           25   Bowled         Adam Milne           4
Mahmudulla(C)         3            3      LBW   Mitchell Santner           5
Afif Hossain          8            3      LBW        Trent Boult           6
Shamim Hossain        0            1   Bowled        Trent Boult           7
Mahedi Hasan         11            5   Caught        Tim Southee           8
Taskin Ahmed         30           12   Caught          Ish Sodhi           9
Mustafizur Rahman    39           17   Bowled         Adam Milne          10
Shoriful Islam        9            3  NOT OUT                             11

In [315]:
new_headers = ['Bowling','Balls','Runs','Wickets']
df_bowler_list_first_ing.columns = new_headers
df_bowler_list_first_ing_without_index = df_bowler_list_first_ing.set_index('Bowling')
df_bowler_list_first_ing_without_index

                  Balls  Runs  Wickets
Bowling
Mitchell Santner     12    33        1
Trent Boult          18    37        3
Tim Southee          18    40        2
Ish Sodhi            18    41        2
Adam Milne           14    39        2

In [316]:
# this is the way to write data to excel file
# Creating Excel Writer Object from Pandas  

writer = pd.ExcelWriter('test.xlsx',engine='xlsxwriter')   
workbook=writer.book
worksheet=workbook.add_worksheet('Validation')
writer.sheets['Validation'] = worksheet
df_score_card_first_ing.to_excel(writer,sheet_name='Validation',startrow=0 , startcol=0)   
df_bowler_list_first_ing.to_excel(writer,sheet_name='Validation',startrow=19, startcol=0)  

writer.save()
writer.close()

C:\Users\nadun\AppData\Local\Programs\Python\Python39\lib\site-packages\xlsxwriter\workbook.py:339: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")

# Next the second innings start and as explained above the algorithm needs to generate random figures.

In [317]:
# import random
# import pandas as pd
# from operator import itemgetter


second_ing_total = 0
second_ing_wickets = 0
balls = 1
TOTAL_WICKETS = 10
TOTAL_BALLS = 120
score_card_second_ing = []


batsman_onstrike = [['name', 0, 0], True]
batsman_offstrike = [['name', 0, 0], False]


bowler_onstrike = []


# batsman_name , runs , balls_faced , method of dismissal , bowler
#importing batting team
batting_url = team_to_bowl[1]
batting_team = pd.read_excel(batting_url)
#converting excel to python list
yet_to_bat = batting_team.values.tolist()   




# bowlers_name , balls , runs , wickets
#importing bowling team
bowling_url = team_to_bat[1]
bowling_team = pd.read_excel(bowling_url)
#converting excel to python list
bowling_team_list = bowling_team.values.tolist()  


yet_to_bowl = []


for i in reversed(range(len(bowling_team_list))):
    if len(yet_to_bowl) < 5 :
        yet_to_bowl.append([bowling_team_list[i][0], 0, 0, 0])



dismissed_batsmen = []
batsman_list = []



# method of dismissal
method_of_dismissal = ['Bowled', 'Caught', 'LBW']


bowler_score = 0  # score counting variable for bowler
batter_score = 0  # score counting variable for batsman


# opening batsmen coming to the field
batsman_onstrike[0] = yet_to_bat.pop(0)
batsman_offstrike[0] = yet_to_bat.pop(0)


# opening bowler
bowler_onstrike = yet_to_bowl.pop(0)


while (balls < (TOTAL_BALLS+1)):
    if ( (second_ing_wickets == TOTAL_WICKETS) or (second_ing_total > first_ing_total) ) :
        break
    else:
        if ((balls-1) > 0 and (balls-1) % 6 == 0) and (len(yet_to_bowl)) > 0:
            yet_to_bowl.append(bowler_onstrike)
            # bowler_onstrike[0] = []
            bowler_onstrike = yet_to_bowl.pop(0)

        # get random scores for bowler and batsman
        bowler_score = random.randint(1, 6)
        batter_score = random.randint(0, 6)

        if bowler_score == batter_score:
            # adding wickets to bowler
            current_bowler_onstrike_second_ing_wickets = 0
            current_bowler_onstrike_second_ing_wickets = bowler_onstrike[3]
            bowler_onstrike[3] = current_bowler_onstrike_second_ing_wickets + 1
            # adding balls to batsman
            current_batsman_onstrike_balls = batsman_onstrike[0][2]
            batsman_onstrike[0][2] = current_batsman_onstrike_balls + 1

            # moving the dismissed_batsmen to dismissed_batsmen array
            dismissed_batsmen.append(batsman_onstrike[0])


            # adding method of dismissal to batsman
            current_batsman_method_of_dismissal = random.choices(
                method_of_dismissal)
            batsman_onstrike[0][3] = current_batsman_method_of_dismissal[0]

            # adding dismissed bowler name to batsman
            current_batsman_bowler_dismissed = batsman_onstrike[0][4]
            batsman_onstrike[0][4] = current_batsman_bowler_dismissed + \
                str(bowler_onstrike[0])

            # fall of wickets
            print('FOW', second_ing_total, ' --> ', second_ing_wickets+1, ' on over -', int(balls/6), '.', (balls) % 6 , batsman_onstrike[0][0])

            #bring new batsman to the crease (batsman_onstrike)
            if len(yet_to_bat) > 0:
                batsman_onstrike[0] = []
                batsman_onstrike[0] = yet_to_bat.pop(0)


            # out - add wicket to wickets
            second_ing_wickets += 1



        else:
            # adding batter_score to current_batsman
            current_batsman_onstrike_score = 0
            current_batsman_onstrike_score = batsman_onstrike[0][1]
            batsman_onstrike[0][1] = current_batsman_onstrike_score + batter_score

            # adding balls to current_batsman
            current_batsman_onstrike_balls = batsman_onstrike[0][2]
            batsman_onstrike[0][2] = current_batsman_onstrike_balls + 1

            # adding batter_score to current_bowler
            current_bowler_onstrike_runs = 0
            current_bowler_onstrike_runs = bowler_onstrike[2]
            bowler_onstrike[2] = current_bowler_onstrike_runs + batter_score

            # swapping onstrike batsman when strike rotates
            if batter_score == 1 or batter_score == 3:
                current_batsman = batsman_onstrike[0]
                # swapping onstrike batsman
                batsman_onstrike[0] = batsman_offstrike[0]
                batsman_offstrike[0] = current_batsman
            else:
                pass  # when batter_score is not swapping

            # add batter score to second_ing_total
            second_ing_total += batter_score

    # adding balls to bowler
    current_bowler_onstrike_balls = 0
    current_bowler_onstrike_balls = bowler_onstrike[1]
    bowler_onstrike[1] = current_bowler_onstrike_balls + 1
    balls += 1

# last dismissed batsman
# last_dismissal = dismissed_batsmen[-1]
# print('Last dismissal', last_dismissal)

#add dismissed_batsmen to batsman_list
batsman_list = dismissed_batsmen

#add each batsman in yet_to_bat to batsman_list array for displaying purposes
if len(yet_to_bat) > 0 :
    for i in range(len(yet_to_bat)):
        batsman_list.append(yet_to_bat[i])

#add on and off strike batsmen to batsman_list
if second_ing_wickets != TOTAL_WICKETS:
    batsman_onstrike[0][3] = '* NOT OUT'
    batsman_list.append(batsman_onstrike[0])

batsman_offstrike[0][3] = 'NOT OUT'
batsman_list.append(batsman_offstrike[0])

#add batsman_list to score_card_second_ing
score_card_second_ing = batsman_list


# Total
# print(' Total-', second_ing_total, ' wickets -', second_ing_wickets, ' overs -', int((balls-1)/6), '.', (balls-1) % 6, ' balls', (balls-1))

# sort score_card_second_ing to the original batting order
sorted_list = sorted(score_card_second_ing, key=itemgetter(5))

# Print score_card_second_ing in a data frame
df_score_card_second_ing = pd.DataFrame(sorted_list)
# print(df_score_card_second_ing)


#add bowlers to bowler_list_second_ing
bowler_list_second_ing = yet_to_bowl
bowler_list_second_ing.append(bowler_onstrike)

df_bowler_list_second_ing = pd.DataFrame(bowler_list_second_ing)
# print(df_bowler_list_second_ing)

FOW 17  -->  1  on over - 0 . 5 Martin Guptill
FOW 20  -->  2  on over - 1 . 1 Daryl Mitchell
FOW 20  -->  3  on over - 1 . 2 Devon Conway
FOW 33  -->  4  on over - 2 . 1 Kane Williamson(C)
FOW 33  -->  5  on over - 2 . 2 James Neesham
FOW 33  -->  6  on over - 2 . 3 Mitchell Santner
FOW 82  -->  7  on over - 5 . 0 Glenn Phillips
FOW 164  -->  8  on over - 9 . 1 Adam Milne
FOW 164  -->  9  on over - 9 . 2 Tim Southee

In [318]:
print('\nTotal-', second_ing_total, '\nwickets -', second_ing_wickets, '\novers -', int((balls-1)/6), '.', (balls-1) % 6, '\nballs', (balls-1))
print('\nLast dismissal', last_dismissal)

Total- 193
wickets - 9
overs - 10 . 4
balls 64

Last dismissal ['Mustafizur Rahman', 39, 17, 'Bowled', ' Adam Milne', 10]

In [319]:
new_headers = ['Batting','Runs','Balls Faced','MOD','Bowler','Batting No']
df_score_card_second_ing.columns = new_headers
df_score_card_second_ing_without_index = df_score_card_second_ing.set_index('Batting')
df_score_card_second_ing_without_index

,Runs,Balls Faced,MOD,Bowler,Batting No
Batting,,,,,
Martin Guptill,17,5,Caught,Shoriful Islam,1
Daryl Mitchell,0,1,Bowled,Mustafizur Rahman,2
Kane Williamson(C),10,4,Bowled,Taskin Ahmed,3
Devon Conway,0,1,Bowled,Mustafizur Rahman,4
Glenn Phillips,39,12,LBW,Shamim Hossain,5
James Neesham,0,1,Caught,Taskin Ahmed,6
Mitchell Santner,0,1,LBW,Taskin Ahmed,7
Adam Milne,70,23,Caught,Shamim Hossain,8
Ish Sodhi,36,9,* NOT OUT,,9
Tim Southee,0,1,LBW,Shamim Hossain,10
Trent Boult,21,6,NOT OUT,,11

In [320]:
new_headers = ['Bowling','Balls','Runs','Wickets']
df_bowler_list_second_ing.columns = new_headers
df_bowler_list_second_ing_without_index = df_bowler_list_second_ing.set_index('Bowling')
df_bowler_list_second_ing_without_index

                   Balls  Runs  Wickets
Bowling
Mustafizur Rahman     12    30        2
Taskin Ahmed          12    32        3
Mahedi Hasan          12    48        0
Shamim Hossain        12    28        3
Shoriful Islam        16    55        1

In [321]:
from openpyxl import load_workbook

book = load_workbook('test.xlsx')
writer = pd.ExcelWriter('test.xlsx', engine='openpyxl') 
writer.book = book

## ExcelWriter for some reason uses writer.sheets to access the sheet.
## If you leave it empty it will not know that sheet Main is already there
## and will create a new sheet.

writer.sheets = dict((ws.title, ws) for ws in book.worksheets)


df_score_card_second_ing.to_excel(writer,sheet_name='Validation',startrow=0 , startcol=9)   
df_bowler_list_second_ing.to_excel(writer,sheet_name='Validation',startrow=19, startcol=9)  

writer.save()

In [322]:
# # this is the way to write data to excel file
# # Creating Excel Writer Object from Pandas  

# summary = pd.read_excel('test.xlsx')

# writer = pd.ExcelWriter('test.xlsx',engine='xlsxwriter')   
# workbook=writer.book
# worksheet=workbook.add_worksheet('Validation')
# writer.sheets['Validation'] = worksheet

# df_score_card_second_ing.to_excel(writer,sheet_name='Validation',startrow=0 , startcol=9)   
# df_bowler_list_second_ing.to_excel(writer,sheet_name='Validation',startrow=19, startcol=9)  

# writer.save()
# writer.close()

# Display match summary for a given match

In [323]:
if selection == toss:
    print(visiting_team[0].replace('_', ' '), 'won the toss and chose to', choose)
else:
    print(home_team[0].replace('_', ' '), 'won the toss and chose to', choose)

Delhi NewZealand won the toss and chose to bowl

## first innings

In [324]:
print(team_to_bat[0].replace('_', ' '))
print(df_score_card_first_ing_without_index.nlargest(4, 'Runs'))


print('\n',team_to_bowl[0].replace('_', ' '))
print(df_bowler_list_first_ing_without_index.nlargest(3, 'Wickets'))

print('\nTotal',first_ing_total,'/',first_ing_wickets)

RoyalChallengers Bangladesh
                   Runs  Balls Faced     MOD        Bowler  Batting No
Batting
Mushfiqur Rahim      70           25  Bowled    Adam Milne           4
Mustafizur Rahman    39           17  Bowled    Adam Milne          10
Taskin Ahmed         30           12  Caught     Ish Sodhi           9
Mahedi Hasan         11            5  Caught   Tim Southee           8

 Delhi NewZealand
             Balls  Runs  Wickets
Bowling
Trent Boult     18    37        3
Tim Southee     18    40        2
Ish Sodhi       18    41        2

Total 190 / 10

## second innings

In [325]:
print(team_to_bowl[0].replace('_', ' '))
print(df_score_card_second_ing_without_index.nlargest(4, 'Runs'))

print('\n',team_to_bat[0].replace('_', ' '))
print(df_bowler_list_second_ing_without_index.nlargest(3, 'Wickets'))

print('\nTarget',first_ing_total+1)
print('Total',second_ing_total,'/',second_ing_wickets)

Delhi NewZealand
                Runs  Balls Faced        MOD           Bowler  Batting No
Batting
Adam Milne        70           23     Caught   Shamim Hossain           8
Glenn Phillips    39           12        LBW   Shamim Hossain           5
Ish Sodhi         36            9  * NOT OUT                            9
Trent Boult       21            6    NOT OUT                           11

 RoyalChallengers Bangladesh
                   Balls  Runs  Wickets
Bowling
Taskin Ahmed          12    32        3
Shamim Hossain        12    28        3
Mustafizur Rahman     12    30        2

Target 191
Total 193 / 9

In [326]:
if (second_ing_total > first_ing_total) :
    # print('second_ing_total',second_ing_total)
    print(team_to_bowl[0].replace('_', ' ') , 'Won by' ,TOTAL_WICKETS-second_ing_wickets , 'wickets')
elif (second_ing_total < first_ing_total):
    # print('first_ing_total',first_ing_total) 
    print(team_to_bat[0].replace('_', ' ' ), 'Won by' , (first_ing_total-second_ing_total) , 'runs')
else :
    print('Match drawn')

Delhi NewZealand Won by 1 wickets

# Store team/player and match information in a text file

# Load team/player and match data once you restart the application